name: "Clone and Install"
description: "Clones repository and sets up Node environment"
runs:
  using: "composite"
  steps:
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm install
      shell: bash
